### ISSUE TITLE
Installs fine about a month ago, now fails

### ISSUE THREAD

**Issue by WinndyBoy** [gripped/odroid-u2-pkgbuilds#3]
Hi thanks for putting all this together, and sharing what you know and have done... I'm just trying to learn things... Your instructions and repo installed fine a month ago, now I come to reinstall again and I think theres a problem with the version of xorg-server-dsd and xf86-input-evdev are in conflict (X-ABI-XINPUT_VERSION). Remove xf86-input-evdev

I thought I'd try and rebuild all the packages with makepkg, so did a git clone of odroid-u2-pkgbuilds... but just don't know which package to start with, any help ?

thanks

sudo pacman -S linux-odroidu-r4p0 mali-odroid-r4p0 xf86-video-armsoc-dsd xorg-server-dsd
[sudo] password for dudman: 
warning: linux-odroidu-r4p0-3.8.13.23-1 is up to date -- reinstalling
warning: mali-odroid-r4p0-1-3 is up to date -- reinstalling
warning: xf86-video-armsoc-dsd-1:213.164e3ca-1 is up to date -- reinstalling
resolving dependencies...
looking for inter-conflicts...
:: xorg-server-dsd and xf86-input-evdev are in conflict (X-ABI-XINPUT_VERSION). Remove xf86-input-evdev? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: xorg-server-dsd: requires xf86-input-evdev
synchronizing filesystem...
[dudman@u33 ~]$

**Comment by WinndyBoy** [comment]
I installed a new version of xf86-input-evdev-git which solved the problem

**Comment by gripped** [comment]
Glad you got it working.
I haven't had time to work on this for a while.
But I'm currently updating my XU repo and will have a look at the U3 one next.
